import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

export const metadata = {
  title:
    "Diffusible - Explore the World of Creative Content Generated by the Community",
  description:
    "Discover and Connect with Creative Content Generated by the Community on Diffusible. We are where creators find inspiration, feedback, community, and opportunities. Your ultimate resource to explore and connect with content creators worldwide.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
